#!/bin/sh
set -e

if command -v update-alternatives >/dev/null 2>&1; then
  update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator \
    /usr/bin/el-terminal 50
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -f /usr/share/icons/hicolor >/dev/null 2>&1 || true
fi

if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database -q /usr/share/applications >/dev/null 2>&1 || true
fi
