#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
  if command -v update-alternatives >/dev/null 2>&1; then
    update-alternatives --remove x-terminal-emulator /usr/bin/el-terminal || true
  fi
fi
