[env]
PKG_CONFIG_PATH = { value = ".local-deps/usr/lib/x86_64-linux-gnu/pkgconfig", relative = true, force = false }
LD_LIBRARY_PATH = { value = ".local-deps/usr/lib/x86_64-linux-gnu", relative = true, force = false }
